version: '3'

services:
  db:
    container_name: db_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    restart: always
    networks:
      - accountant
    volumes:
      - postgres:/var/www/accountant/docker-volumes/postgres
    ports:
      - 127.0.0.1:5432:5432

  db_pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ainurikdav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/www/accountant/docker-valumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - accountant
    restart: always

networks:
  accountant:
    driver: bridge

volumes:
  postgres:
  pgadmin:
