version: '3'

services:
  server:
    build: ./
    container_name: accountant-server
    restart: always
    volumes:
      - ./src/:/app/src
    ports:
      - '4200:4200'
    depends_on:
      - pgdb
    networks:
      - accountant
  pgdb:
    container_name: pgdb
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    networks:
      - accountant
    volumes:
      - db:/var/www/accountant/docker-volumes/postgres
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - accountant
    environment:
      PGADMIN_DEFAULT_EMAIL: ainurikdav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/www/accountant/docker-volumes/pgadmin
    ports:
      - '80:80'
    restart: always

networks:
  accountant:
    driver: bridge

volumes:
  db:
  pgadmin:
