version: '3'

services:
  pgdb:
    container_name: pgdb
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    networks:
      - accountant
    volumes:
      - dbdatatest:/var/www/accountant/docker-volumes/postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - accountant
    environment:
      PGADMIN_DEFAULT_EMAIL: ainurikdav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmintest:/var/www/accountant/docker-volumes/pgadmin
    ports:
      - "80:80"
    restart: always

networks:
  accountant:
    driver: bridge

volumes:
  dbdatatest:
  pgadmintest:
